apiVersion: v1
kind: Service
metadata:
  name: my-app-stable
  namespace: flask
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30097
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-canary
  namespace: flask
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30098
  type: NodePort
